all:
	g++ -o3 --std=c++11 tcp_client.cpp -o tcp_client -lboost_system -pthread
	g++ -o3 --std=c++11 tcp_server.cpp -o tcp_server -lboost_system -pthread
	g++ -o3 --std=c++11 udp_client.cpp -o udp_client -lboost_system -pthread